/** Single published ruleset for new paid rooms; old matches retain v1 geometry. */
export const LUDO_LAUNCH_RULES = [
  { title: "Entry and start", text: "Paid Ludo requires four distinct paying human wallets, each entering with 0.002 native ETH on the displayed Robinhood network. Bots are only for free practice. Ready within 2 minutes; if all four are not ready within 5 minutes of the first entry, remaining entries are refunded. A random seat starts." },
  { title: "Movement", text: "BOARD Ludo v2 uses a 52-square shared circuit, four pawns each, and one six-sided die. A 6 brings a yard pawn onto its start square; it does not move that pawn six more spaces. Otherwise choose one legal pawn and move exactly the roll. You do not need a capture to enter your private home lane." },
  { title: "Extra rolls", text: "A 6, a capture, or finishing a pawn grants one extra roll. If a 6 has no legal move, you still roll again. Three consecutive sixes void only the third roll and end the turn; earlier moves stand. A non-six resets the streak. No legal move on a non-six passes the turn." },
  { title: "Captures and blockades", text: "Landing on a single opponent on an unsafe shared square sends it to its yard. Star and coloured start squares are safe from capture. Two or more pawns of one colour form a blockade, including on safe squares: opponents cannot land on or pass it. Your own pawns may pass or join your blockade. Eliminated players do not block the board." },
  { title: "Home and winning", text: "Finish each pawn by exact count; an overshoot is not legal. First to finish all four wins, or the last remaining player wins if all rivals forfeit or are eliminated. No runner-up payout. A finished match cannot be played again." },
  { title: "Clock and disconnection", text: "Each roll or move decision has a 15-second server deadline. Missing either decision passes your turn and discards any unused roll; three missed decisions across the match eliminate you. Closing the browser does not pause the match. Leaving after the start forfeits your entry into the pot." },
  { title: "Where money goes", text: "Entries go directly to an operator-controlled treasury wallet, not a game escrow smart contract. Four entries form 0.008 ETH: 0.00016 ETH (2%) remains in the treasury and 0.00784 ETH (98%) is sent to the winning wallet. No automatic buyback, burn, or fee-split transfer is implemented for these entries. You pay entry transaction gas; the operator pays payout and refund gas." },
  { title: "Refunds and settlement", text: "Leaving before the start or an expired waiting room queues a full 0.002 ETH refund. A submitted transfer is not a confirmed payment. The worker retries saved payout/refund transactions; receipts and saved results are available in My matches and refunds, including after table reuse. Chain outages, insufficient treasury gas, and reverted transfers can delay payment and require operator recovery." },
  { title: "Trust and launch status", text: "Dice and game state are server-authoritative, using server-side cryptographic randomness; they are not on-chain or independently verifiable randomness. Monopoly is disabled: Work in progress. Testnet ETH is not mainnet ETH. Mainnet entries remain disabled until explicitly approved and the payment/game worker is healthy. Historical wallet accounts may require ownership review; their records and balances are preserved." },
] as const;
